# Generated by Django 5.1.5 on 2025-01-26 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_remove_parentprofile_associated_students_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentstudentmapping',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_mappings', to='testapp.parentprofile'),
        ),
        migrations.AlterField(
            model_name='parentstudentmapping',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_mappings', to='testapp.studentprofile'),
        ),
    ]
