# Generated by Django 5.1.5 on 2025-01-27 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_alter_studentprofile_enrollment_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parentstudentmapping',
            name='relationship',
        ),
    ]
